version: '3.7'

services:
  app:
    image: laravel-app:k
    env_file: .env
    restart: always
    ports:
      - "8013:80"
    volumes:
      - ./.env:/var/www/app/.env
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3305:3306"
    restart: always
    env_file: .env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
