name: Build Container Image

# When its time to do a release do a full cross platform build for all supported
# architectures and push all of them to Docker Hub.
# Only trigger on semver shaped tags.
# Ref: https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/release.yml
on:
  pull_request:
    paths:
      - "alpine/5/**"
  push:
    paths:
      - "alpine/5/**"
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-5-${{ hashFiles('config/cache_buster') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-5-${{ hashFiles('config/cache_buster') }}-

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./alpine/5/
          build-args: INVOICENINJA_VERSION=5-develop
          target: prod
          platforms: linux/amd64,linux/arm64
          tags: invoiceninja/invoiceninja:cache
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache